<a href="https://colab.research.google.com/github/abanis24/NLP-Practice/blob/main/Word_embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [4]:
# !pip install tensorflow-gpu
# !pip install tensorflow[and-cuda]
!pip install tensorflow

In [5]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [6]:
##tensorflow >2.0
# from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.text import one_hot

In [7]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [8]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [9]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [10]:
'''onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)'''
onehot_repr = [one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[105, 158, 368, 265], [105, 158, 368, 101], [105, 194, 368, 427], [312, 357, 295, 261, 464], [312, 357, 295, 261, 272], [435, 105, 61, 368, 233], [420, 283, 287, 261]]


### Word Embedding Represntation

In [11]:
'''from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential'''
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [13]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 105 158 368 265]
 [  0   0   0   0 105 158 368 101]
 [  0   0   0   0 105 194 368 427]
 [  0   0   0 312 357 295 261 464]
 [  0   0   0 312 357 295 261 272]
 [  0   0   0 435 105  61 368 233]
 [  0   0   0   0 420 283 287 261]]


In [14]:
## 10 feature dimesnions
dim=10


In [17]:
'''model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')'''
model = Sequential()
model.add(Embedding(voc_size,10))
model.compile('adam','mse')

In [23]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ (8, 10)                     │           5,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 105, 158, 368, 265], dtype=int32)

In [25]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


array([[ 0.01878572, -0.03525577,  0.02479955, -0.00606541,  0.04132917,
        -0.02975788,  0.02289892, -0.01249591, -0.01628054, -0.01118242],
       [ 0.01878572, -0.03525577,  0.02479955, -0.00606541,  0.04132917,
        -0.02975788,  0.02289892, -0.01249591, -0.01628054, -0.01118242],
       [ 0.01878572, -0.03525577,  0.02479955, -0.00606541,  0.04132917,
        -0.02975788,  0.02289892, -0.01249591, -0.01628054, -0.01118242],
       [ 0.01878572, -0.03525577,  0.02479955, -0.00606541,  0.04132917,
        -0.02975788,  0.02289892, -0.01249591, -0.01628054, -0.01118242],
       [ 0.00990685,  0.02492467,  0.04534305, -0.01427207,  0.01106985,
         0.03040281, -0.04145432,  0.04460646,  0.02304595,  0.0462783 ],
       [ 0.01027676,  0.04575106,  0.02915125,  0.04087034, -0.03839312,
         0.00966159,  0.01667869,  0.04839731,  0.04227487, -0.03183683],
       [ 0.00038654, -0.03606602,  0.00253127, -0.02263746,  0.0237648 ,
        -0.0273914 ,  0.02973241,  0.00835053

In [33]:
print(model.predict(embedded_docs[6]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
[[ 1.87857188e-02 -3.52557674e-02  2.47995518e-02 -6.06540591e-03
   4.13291715e-02 -2.97578815e-02  2.28989236e-02 -1.24959126e-02
  -1.62805431e-02 -1.11824162e-02]
 [ 1.87857188e-02 -3.52557674e-02  2.47995518e-02 -6.06540591e-03
   4.13291715e-02 -2.97578815e-02  2.28989236e-02 -1.24959126e-02
  -1.62805431e-02 -1.11824162e-02]
 [ 1.87857188e-02 -3.52557674e-02  2.47995518e-02 -6.06540591e-03
   4.13291715e-02 -2.97578815e-02  2.28989236e-02 -1.24959126e-02
  -1.62805431e-02 -1.11824162e-02]
 [ 1.87857188e-02 -3.52557674e-02  2.47995518e-02 -6.06540591e-03
   4.13291715e-02 -2.97578815e-02  2.28989236e-02 -1.24959126e-02
  -1.62805431e-02 -1.11824162e-02]
 [-8.02689791e-03 -2.30887663e-02 -4.75142002e-02 -8.41505826e-05
   1.55586042e-02 -3.46458778e-02 -1.85884535e-04  3.27861644e-02
  -3.88698690e-02 -4.12181504e-02]
 [ 3.67539190e-02  1.07333064e-02  4.11390178e-02 -4.38436046e-02
  -4.26291116e-02 -4.52697985e-02 -4.86894250e-02 -2.20787171

In [29]:
embedded_docs[0]

array([  0,   0,   0,   0, 105, 158, 368, 265], dtype=int32)

In [ ]:
print(model.predict(embedded_docs)[0])

[[-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.03786323 -0.02628061  0.02974111 -0.03307171  0.0271405   0.00945134
   0.02378127  0.04176904  0.00514941  0.0152082 ]
 [ 0.04834186  0.04388311 -0.02802253 -0.01475487 -0.01212303  0.03762435
  -0.01166249 -0.02141088  0.04654533  0.01537322]
 [ 0.03276015 -0.00637691  0.03907344 -0.01912468  0.02177186 -0.04630325
   0.00800942 -0.03115667 -0.00486455 -0.04843524]
 [-0.04173617  0.03438064  0.02880521 -0.01896455  0.0323303  -0.00109453
  -0.01675171 -0.00941917 -0.03309294 -0.04779492]]

In [35]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [36]:
sent

['The world is a better place',
 'Marvel series is my favourite movie',
 'I like DC movies',
 'the cat is eating the food',
 'Tom and Jerry is my favourite movie',
 'Python is my favourite programming language']

In [37]:
voca_size=500

In [38]:
# one hot representation
one_hot_repr = [one_hot(words,voca_size) for words in sent]
print(one_hot_repr)

[[105, 288, 46, 295, 370, 248], [460, 96, 46, 45, 101, 442], [312, 89, 172, 397], [105, 297, 46, 122, 105, 131], [162, 267, 493, 46, 45, 101, 442], [456, 46, 45, 101, 263, 220]]


In [40]:
# Padding the words present in each sent
from tensorflow.keras.preprocessing.sequence import pad_sequences
sent_length = 10
padd_seq = pad_sequences(one_hot_repr,padding='pre', maxlen=sent_length)
print(padd_seq)

[[  0   0   0   0 105 288  46 295 370 248]
 [  0   0   0   0 460  96  46  45 101 442]
 [  0   0   0   0   0   0 312  89 172 397]
 [  0   0   0   0 105 297  46 122 105 131]
 [  0   0   0 162 267 493  46  45 101 442]
 [  0   0   0   0 456  46  45 101 263 220]]


In [41]:
# model
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential

model=Sequential()
model.add(Embedding(voca_size,10))
model.compile('adam','mse')

In [43]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [44]:
padd_seq[0]

array([  0,   0,   0,   0, 105, 288,  46, 295, 370, 248], dtype=int32)

In [45]:
model.predict(padd_seq[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step


array([[-0.00113909,  0.04107455,  0.01050911,  0.00066594, -0.00840565,
        -0.00031366,  0.01426527,  0.03600684, -0.00165049,  0.00340573],
       [-0.00113909,  0.04107455,  0.01050911,  0.00066594, -0.00840565,
        -0.00031366,  0.01426527,  0.03600684, -0.00165049,  0.00340573],
       [-0.00113909,  0.04107455,  0.01050911,  0.00066594, -0.00840565,
        -0.00031366,  0.01426527,  0.03600684, -0.00165049,  0.00340573],
       [-0.00113909,  0.04107455,  0.01050911,  0.00066594, -0.00840565,
        -0.00031366,  0.01426527,  0.03600684, -0.00165049,  0.00340573],
       [ 0.02561079,  0.04734871,  0.04472494, -0.03642384, -0.02713159,
         0.02935867, -0.03260072,  0.0058764 ,  0.01310078, -0.00857349],
       [-0.01922582,  0.02134449,  0.02545093, -0.03828452,  0.04597969,
         0.00797737, -0.0297471 , -0.01079444, -0.02966813, -0.04743382],
       [-0.00179283, -0.00758095, -0.02847612,  0.01494744,  0.0362514 ,
        -0.01299313, -0.04619328,  0.02057019